### PR TITLE
allow client to be fully configurable via ENV variables

### PR DESCRIPTION
**Pull request by seuros**
This change mirror how PG support PGUSER, PGPASSWORD .

reference: https://www.postgresql.org/docs/current/libpq-envars.html

### CODE REVIEW

**Comment by ankane** [comment]
Hi @seuros, thanks for the PR. These can all be set with the current environment variable (`IMMUDB_URL`), so I don't think others are needed.

**Comment by seuros** [comment]
@ankane I know about the IMMUDB_URL, but in my setup, i set just the user and password in the vault. 

This is valid for both mysql and PG, and currently i'm trying to build an ActiveRecord adapter that has similar pattern using this gem.

**Comment by ankane** [comment]
You can include the logic in application code or the Active Record adapter if needed, but it's not something I'd like to include in this gem.

**Comment by seuros** [comment]
Fair enough.

**Pull request closed without merging**
